/**
 * Comprehensive Vietnamese Phonetic Reading Guide
 * (Phiên âm Tiếng Việt / Hướng dẫn đọc giống Tiếng Việt chuẩn chỉnh theo SGK Tiếng Anh Lớp 6 Global Success)
 */

// 1. Exact curated pronunciation for every vocabulary item by Word ID
export const EXACT_WORD_VIET_READING_BY_ID: Record<string, string> = {
  // Unit 1: My New School
  u1_1: 'ré-đi',
  u1_2: 'niu',
  u1_3: 'mít-t',
  u1_4: 'xcu-l (xờ-kun)',
  u1_5: 'hé-vi',
  u1_6: 'x-mát-t',
  u1_7: 'xpe-sồ',
  u1_8: 'xắp-dịch-t',
  u1_9: 'diu-ni-phom',
  u1_10: 'pen-sồ sa-pơ-nơ',
  u1_11: 'pen-sồ cây-s',
  u1_12: 'rắp-bơ',
  u1_13: 'kheo-kiu-lây-tờ',
  u1_14: 'hít-xtơ-ri',
  u1_15: 'mát-th (thổi nhẹ)',
  u1_16: 'xai-ân-s',
  u1_17: 'khăm-pớt-s',
  u1_18: 'kla-x-rum',
  u1_19: 'hôm-uớc-k',
  u1_20: 'kla-x-mây-ts',
  u1_21: 'bo-đinh xcu-l',
  u1_22: 'ru-lơ',

  // Unit 2: My House
  u2_1: 'lí-ving rum',
  u2_2: 'bét-rum',
  u2_3: 'kít-chừn',
  u2_4: 'bát-th-rum',
  u2_5: 'tao-n-hao-s',
  u2_6: 'ph-lét-t',
  u2_7: 'ph-rít-d',
  u2_8: 'đít-sh-oa-sơ',
  u2_9: 'chét-st ơv đrô-z',
  u2_10: 'oa-đrô-b',
  u2_11: 'bi-hain-đ',
  u2_12: 'bi-tuy-n',
  u2_13: 'in ph-răn-t ơv',
  u2_14: 'ăn-đờ',
  u2_15: 'búc-k-seo-ph',
  u2_16: 'đe-cơ-rây-t',
  u2_17: 'pí-lâu',
  u2_18: 'chóp-x-tích-s',

  // Unit 3: My Friends
  u3_1: 'ph-ren-đ-li',
  u3_2: 'k-le-vờ',
  u3_3: 'khain-đ',
  u3_4: 'kri-ê-típ-v',
  u3_5: 'khon-phi-đừn-t',
  u3_6: 'hát-đ uếc-king',
  u3_7: 'xai (shai)',
  u3_8: 'khe-phun',
  u3_9: 'khơ-li he-ơ',
  u3_10: 'b-lon-đ',
  u3_11: 'g-la-xịt-z',
  u3_12: 'píc-ních',
  u3_13: 'bít-x-kịt',
  u3_14: 'éc-típ-v',
  u3_15: 'phăn-ni',
  u3_16: 'khom-míc búc-k',
  u3_17: 'vai-ơ-lin',

  // Unit 4: My Neighbourhood
  u4_1: 'nây-bơ-hút-đ',
  u4_2: 'noi-zi',
  u4_3: 'quai-ợt',
  u4_4: 'lai-v-li',
  u4_5: 'khơn-vi-ni-ừn-t',
  u4_6: 'khơ-thi-đrồ',
  u4_7: 'them-pồ',
  u4_8: 'rêu-uây x-tây-shừn',
  u4_9: 'x-que',
  u4_10: 'đi-li-shớt-s',
  u4_11: 'pâu-xt óph-phịt-s',
  u4_12: 'miu-zi-ừm',
  u4_13: 'k-rao-địt-đ',
  u4_14: 'ne-râu',
  u4_15: 'xắp-bớp-z',

  // Unit 5: Natural Wonders of Viet Nam
  u5_1: 'oăn-đờ',
  u5_2: 'ai-lừn-đ',
  u5_3: 'oa-tờ-pho',
  u5_4: 'kêy-v',
  u5_5: 'đe-zợt',
  u5_6: 'mao-n-từn',
  u5_7: 'xăn-x-kri-n',
  u5_8: 'x-li-ping béc-g',
  u5_9: 'béc-k-péc-k',
  u5_10: 'p-la-x-tờ',
  u5_11: 'xít-zơ-z',
  u5_12: 'ếch-x-p-lo',
  u5_13: 'xi-nơ-ri',
  u5_14: 'pho-rịt-xt',

  // Unit 6: Our Tet Holiday
  u6_1: 'gé-đơ-ring-z',
  u6_2: 'lắc-ki ma-ni',
  u6_3: 'phai-ơ-uếc-ks',
  u6_4: 'pít-ch ph-lao-uơ-z',
  u6_5: 're-lơ-típ-v-z',
  u6_6: 'en-vơ-lâu-p-s',
  u6_7: 'khắt-x-từm-z',
  u6_8: 'x-uýt-ts',
  u6_9: 'bi-hêy-v',
  u6_10: 'mít-đ-nait',
  u6_11: 'uýt-sh',
  u6_12: 'trờ-đít-shơ-nồ',

  // Unit 7: Television
  u7_1: 'kha-tun',
  u7_2: 'khom-mơ-đi',
  u7_3: 'chen-nồ',
  u7_4: 'viu-ơ',
  u7_5: 'pop-piu-lơ',
  u7_6: 'bo-ring',
  u7_7: 'uail-đ-laiph',
  u7_8: 'ơ-tréc-kt',
  u7_9: 'in-te-li-dừn-t',
  u7_10: 'te-lừn-t xô',
  u7_11: 'chen-nồ gai-đ',

  // Unit 8: Sports and Games
  u8_1: 'tê-bồ the-nịt-s',
  u8_2: 'kơ-ra-ti',
  u8_3: 'vo-li-bo',
  u8_4: 'chét-s',
  u8_5: 'i-quíp-mừn-t',
  u8_6: 'chem-pi-ừn',
  u8_7: 'ré-kịt',
  u8_8: 'góg-gồ-z',
  u8_9: 'me-rơ-thon',
  u8_10: 'e-rô-bích-s',
  u8_11: 'x-kíp-ping rô-p',
  u8_12: 'khơn-g-rét-chu-lêi-shừn-z',

  // Unit 9: Cities of the World
  u9_1: 'len-đ-mác-k',
  u9_2: 'khe-pi-tồ',
  u9_3: 'thao-uơ',
  u9_4: 'ên-shừn-t',
  u9_5: 'pâu-xt-cát-đ',
  u9_6: 'khôu-st',
  u9_7: 'ví-zi-tờ',
  u9_8: 'thi-ơ-tờ',
  u9_9: 'ếch-xai-ting',
  u9_10: 'phên-tát-x-tíc',

  // Unit 10: Our Houses in the Future
  u10_1: 'phiu-chờ',
  u10_2: 'x-mát-t',
  u10_3: 'xô-lơ',
  u10_4: 'pe-lợt-s',
  u10_5: 'khót-tịt-d',
  u10_6: 'mun',
  u10_7: 'ơ-p-lai-ừn-s',
  u10_8: 'he-li-khóp-tờ',
  u10_9: 'p-le-nịt',
  u10_10: 'i-lếch-tríc',

  // Unit 11: Our Greener World
  u11_1: 'en-vai-rơn-mừn-t',
  u11_2: 'ri-diu-zơ-bồ',
  u11_3: 'rắp-bít-sh',
  u11_4: 'ri-xai-k-ling bin-z',
  u11_5: 'xai-k-ling',
  u11_6: 'p-lan-t',
  u11_7: 'xêy-v',
  u11_8: 'uêi-st',
  u11_9: 'kri-ê-típ-v',
  u11_10: 'ph-lắt-đ-z',

  // Unit 12: Robots
  u12_1: 'rô-bót-t',
  u12_2: 'đu đơ đít-shịt-z',
  u12_3: 'ai-ừn kh-lâu-đ-z',
  u12_4: 'diut-x-phun',
  u12_5: 'mơ-sin-z',
  u12_6: 'hiu-mừn-z',
  u12_7: 'i-lếch-trí-xi-ti',
  u12_8: 'đê-li',
  u12_9: 'im-p-ru-v',
  u12_10: 'in-tơ-né-shơ-nồ',
};

// 2. Exact curated pronunciation for every example sentence by Word ID
export const EXACT_SENTENCE_VIET_READING_BY_ID: Record<string, string> = {
  // Unit 1
  u1_1: 'A diu ré-đi pho xcu-l?',
  u1_2: 'Đít-s iz mai niu xcu-l-béc-g.',
  u1_3: 'Nai-s tu mít-t diu!',
  u1_4: 'Hi gâu-z tu xcu-l év-ri đây.',
  u1_5: 'Đơ béc-g lúc-s hé-vi.',
  u1_6: 'Hi iz vé-ri x-mát-t.',
  u1_7: 'Đít-s iz ơ xpe-sồ đây.',
  u1_8: 'Óat-s do phây-vơ-rịt xắp-dịch-t?',
  u1_9: 'Mai xcu-l diu-ni-phom iz prít-ti.',
  u1_10: 'Ai hép-v ơ rét-đ pen-sồ sa-pơ-nơ.',
  u1_11: 'Ai hép-v ơ kha-lơ-phun pen-sồ cây-s.',
  u1_12: 'Khen ai bo-râu do rắp-bơ?',
  u1_13: 'Ai hép-v ơ niu kheo-kiu-lây-tờ.',
  u1_14: 'Mai phây-vơ-rịt xắp-dịch-t iz hít-xtơ-ri.',
  u1_15: 'Mát-th iz phăn en-đ ếch-xai-ting.',
  u1_16: 'Ai hép-v xai-ân-s on Măn-đây-z.',
  u1_17: 'Ai hép-v ơ niu khăm-pớt-s pho mát-th.',
  u1_18: 'Ao-ơ kla-x-rum iz lát-d en-đ b-rait.',
  u1_19: 'Hi-z đu-inh hiz hôm-uớc-k.',
  u1_20: 'Đu diu ri-mém-bơ do kla-x-mây-ts?',
  u1_21: 'Đây x-tá-đi in ơ bo-đinh xcu-l.',
  u1_22: 'Mai niu ru-lơ iz so-t.',

  // Unit 2
  u2_1: 'Đe-ơ iz ơ xô-pha in đơ lí-ving rum.',
  u2_2: 'Ít-s ơ nai-s en-đ khâu-zi bét-rum.',
  u2_3: 'Đe-z ơ kít-chừn in mai hao-s.',
  u2_4: 'Đe-ơ a tu bát-th-rum-z in mai hao-s.',
  u2_5: 'Ai lip-v in ơ mo-đừn tao-n-hao-s.',
  u2_6: 'Uy a mu-ving tu ơ ph-lét-t néch-st măn-th!',
  u2_7: 'Đe-ơ iz ơ ph-rít-d in mai kít-chừn.',
  u2_8: 'Ai hép-v ơ đít-sh-oa-sơ in mai kít-chừn.',
  u2_9: 'Ai hép-v oăn chét-st ơv đrô-z.',
  u2_10: 'Ai kíp mai kh-lâu-đ-z in mai oa-đrô-b.',
  u2_11: 'Iz đơ mao-s bi-hain-đ đơ bóc-x?',
  u2_12: 'Đi ép-pồ iz bi-tuy-n đơ b-lóc-s.',
  u2_13: 'Đi e-li-phừn-t iz in ph-răn-t ơv đơ che-ơ.',
  u2_14: 'Đơ đóc-g iz ăn-đờ đơ tê-bồ.',
  u2_15: 'Xi héz ơ bích-g búc-k-seo-ph.',
  u2_16: 'Đây đe-cơ-rây-t đơ Krít-x-mợt-s tri.',
  u2_17: 'Đơ khet iz x-li-ping on đơ pí-lâu.',
  u2_18: 'Ai hép-v bo-t niu chóp-x-tích-s.',

  // Unit 3
  u3_1: 'Xi iz ơ vé-ri ph-ren-đ-li ph-ren-đ.',
  u3_2: 'Nam iz ơ k-le-vờ x-tiu-đừn-t.',
  u3_3: 'Hi iz ơ khain-đ en-đ hép-phun boi.',
  u3_4: 'Hi iz ơ kri-ê-típ-v át-tịt-st.',
  u3_5: 'Hi lúc-s vé-ri khon-phi-đừn-t on x-tê-d.',
  u3_6: 'Nam iz ơ hát-đ uếc-king x-tiu-đừn-t.',
  u3_7: 'Mi-na iz xai tu x-píc in pắp-b-lích.',
  u3_8: 'P-li-z bi khe-phun uýt-th đét-t ai-ừn.',
  u3_9: 'Xi héz khơ-li b-rao-n he-ơ.',
  u3_10: 'Xi héz biu-ti-phun b-lon-đ he-ơ.',
  u3_11: 'Xi iz ue-ring x-tai-lít-sh g-la-xịt-z.',
  u3_12: 'Đây hép-v ơ g-rêi-t píc-ních tờ-gé-đơ.',
  u3_13: 'P-li-z pát-s mi xăm bít-x-kịt-s.',
  u3_14: 'Xi iz ơn éc-típ-v x-pót-s gơ-l.',
  u3_15: 'Hi iz phăn-ni en-đ mêi-k-s ắt-s láp-ph.',
  u3_16: 'Phong-z ri-đinh ơ khom-míc búc-k.',
  u3_17: 'Xi iz p-lê-inh đơ vai-ơ-lin.',

  // Unit 4
  u4_1: 'Iz do nây-bơ-hút-đ quai-ợt?',
  u4_2: 'Ít-s ơ vé-ri noi-zi x-trít.',
  u4_3: 'Mai ví-lịt-d iz vé-ri quai-ợt.',
  u4_4: 'Ít iz ơ lai-v-li p-lêi-s tu lip-v in.',
  u4_5: 'Ít-s khơn-vi-ni-ừn-t tu thêi-k ơ bắt-s.',
  u4_6: 'Ai óp-phừn gâu tu đơ khơ-thi-đrồ on Xăn-đây-z.',
  u4_7: 'Diu xút-đ ví-zịt Ngọc Sơn them-pồ.',
  u4_8: 'Đơ rêu-uây x-tây-shừn iz bí-zi.',
  u4_9: 'Iz đe-ơ ơ x-que in do thao-n?',
  u4_10: 'Đơ xi-phút-đ hi-ơ iz đi-li-shớt-s.',
  u4_11: 'Ue-z đơ pâu-xt óph-phịt-s?',
  u4_12: 'Ai ví-zịt đơ miu-zi-ừm oăn-s ơ măn-th.',
  u4_13: 'Đơ x-trít uơ-z tu k-rao-địt-đ.',
  u4_14: 'Đi e-li iz vé-ri ne-râu.',
  u4_15: 'Ai lip-v in đơ xắp-bớp-z ơv Đà Nẵng.',

  // Unit 5
  u5_1: 'Thót-k ơ-bao-t oăn-đơ-z ơv đơ uếc-l-đ.',
  u5_2: 'Việt Nam héz mé-ni biu-ti-phun ai-lừn-đ-z.',
  u5_3: 'Uýt-ch oa-tờ-pho iz in Cao Bằng?',
  u5_4: 'Sơn Đoòng iz ơ méc-ní-phi-xừn-t kêy-v.',
  u5_5: 'Đây uơ in đơ đe-zợt pho nai-n đây-z.',
  u5_6: 'Phan-xi-păng iz đơ hai-ịt-st mao-n-từn.',
  u5_7: 'Ơ-p-lai xăn-x-kri-n bi-pho gâu-inh ao-t.',
  u5_8: 'Hiz x-li-ping béc-g iz uo-m en-đ b-lu.',
  u5_9: 'Đe-ơ a xơ-p-lai-z in mai béc-k-péc-k.',
  u5_10: 'Xi gót ơ p-la-x-tờ pho hơ khắt.',
  u5_11: 'Khút-đ diu pát-s mi đơ xít-zơ-z?',
  u5_12: 'Ai oăn-t tu ếch-x-p-lo đi ai-lừn-đ bai bâu-t.',
  u5_13: 'Đơ xi-nơ-ri hi-ơ iz oăn-đơ-phun.',
  u5_14: 'Ai lắp-v hai-king in đơ g-ri-n pho-rịt-xt.',

  // Unit 6
  u6_1: 'Tết iz ơ thaim pho phe-mơ-li gé-đơ-ring-z.',
  u6_2: 'Diu-l gét lắc-ki ma-ni on Tết.',
  u6_3: 'Óat thaim đu đơ phai-ơ-uếc-ks x-tát?',
  u6_4: 'Uy đe-cơ-rây-t hao-zịt-z uýt-th pít-ch ph-lao-uơ-z.',
  u6_5: 'Uy ví-zịt ao-ơ re-lơ-típ-v-z on Tết.',
  u6_6: 'Rét-đ en-vơ-lâu-p-s b-ring gút-đ lắc.',
  u6_7: 'Tết khắt-x-từm-z in-k-lu-đ k-li-ning hôm.',
  u6_8: 'Chiu-đrừn in-dôi ít-ting Tết x-uýt-ts.',
  u6_9: 'Chiu-đrừn xút-đ bi-hêy-v ueo điu-ring Tết.',
  u6_10: 'Ét Tết mít-đ-nait, phai-ơ-uếc-ks lait ắp.',
  u6_11: 'Uy mêi-k gút-đ uýt-shịt-z pho niu di-ơ.',
  u6_12: 'Đây ue trờ-đít-shơ-nồ Áo Dài.',

  // Unit 7
  u7_1: 'Hi pri-phơ-z oát-ching kha-tun-z.',
  u7_2: 'Khom-mơ-đi mu-viz mêi-k chiu-đrừn láp-ph.',
  u7_3: 'Kha-tun Nét-uớc-k iz ơ phê-mớt-s chen-nồ.',
  u7_4: 'Viu-ơ-z in-dôi en-tơ-têi-ning xô-z.',
  u7_5: 'Đít-s iz đơ môu-st pop-piu-lơ xô.',
  u7_6: 'Đơ phim iz vé-ri bo-ring.',
  u7_7: 'Xô-z ơ-bao-t uail-đ-laiph tít-ch ắt-s nê-chờ.',
  u7_8: 'Ti-vi ơ-tréc-kts viu-ơ-z uýt-th gêm-z.',
  u7_9: 'Đon-phin-z a in-te-li-dừn-t e-ni-mồ-z.',
  u7_10: 'Đét-t miu-zíc te-lừn-t xô iz g-rêi-t.',
  u7_11: 'Chếch-k đơ chen-nồ gai-đ tờ-nait.',

  // Unit 8
  u8_1: 'Hi p-lê-z tê-bồ the-nịt-s év-ri áp-tơ-nun.',
  u8_2: 'Ai đu kơ-ra-ti év-ri Xăn-đây mo-ning.',
  u8_3: 'Vo-li-bo iz ơ pop-piu-lơ tim x-pót.',
  u8_4: 'P-lê-inh chét-s ék-sơ-saiz-z do main-đ.',
  u8_5: 'Đơ dim héz lót-s ơv i-quíp-mừn-t.',
  u8_6: 'Mai-a uơ-z đơ bát-x-kịt-bo chem-pi-ừn.',
  u8_7: 'Se-ra xoăng hơ ré-kịt.',
  u8_8: 'Ai ue xuy-m-ming góg-gồ-z.',
  u8_9: 'E-mi-li trên-đ pho đơ me-rơ-thon.',
  u8_10: 'E-rô-bíc ék-sơ-saiz-z kíp khít-đ-z phịt-t.',
  u8_11: 'Se-ra prác-tít-st uýt-th x-kíp-ping rô-p.',
  u8_12: 'Khơn-g-rét-chu-lêi-shừn-z on do vík-tơ-ri!',

  // Unit 9
  u9_1: 'Bích-g Ben iz ơ len-đ-mác-k ơv Lơn-đơn.',
  u9_2: 'Hà Nội iz đơ khe-pi-tồ xi-ti ơv Việt Nam.',
  u9_3: 'Đi Ép-phen Thao-uơ iz in Pa-ri.',
  u9_4: 'Hội An héz ên-shừn-t x-trít-s.',
  u9_5: 'Ai xen-t ơ pâu-xt-cát-đ ph-rơm Sít-ni.',
  u9_6: 'Đà Nẵng iz phê-mớt-s pho k-li-n khôu-sts.',
  u9_7: 'Thau-zừn-đ-z ơv ví-zi-tơ-z ví-zịt đê-li.',
  u9_8: 'Đơ Sít-ni Ó-pơ-ra Hao-s iz ơ thi-ơ-tờ.',
  u9_9: 'Ếch-x-p-lo-ring Tô-ky-ô iz ếch-xai-ting.',
  u9_10: 'Đơ viu uơ-z phên-tát-x-tíc!',

  // Unit 10
  u10_1: 'In đơ phiu-chờ, hao-zịt-z hép-v rô-bót-s.',
  u10_2: 'X-mát-t hao-zịt-z đu cho-z o-tô-me-tíc-li.',
  u10_3: 'Hao-zịt-z uyn hép-v xô-lơ pe-nồ-z on rup-ph-s.',
  u10_4: 'Xăm phiu-chờ hao-zịt-z lúc lai-k pe-lợt-xịt-z.',
  u10_5: 'Ơ khâu-zi khót-tịt-d in đơ g-ri-n ví-lịt-d.',
  u10_6: 'I-me-dìn lí-ving in ơ đôm on đơ mun.',
  u10_7: 'X-mát-t ơ-p-lai-ừn-xịt-z xêy-v en-nơ-ji.',
  u10_8: 'Ruf-tóp pát-đ-z pho he-li-khóp-tơ-z.',
  u10_9: 'Uy mắt-st prơ-tếch-t ao-ơ g-ri-n p-le-nịt.',
  u10_10: 'I-lếch-tríc ơ-p-lai-ừn-xịt-z hép ắt-s khúc-k.',

  // Unit 11
  u11_1: 'Prơ-tếch-ting đi en-vai-rơn-mừn-t iz ao-ơ điu-ti.',
  u11_2: 'Diu-z ri-diu-zơ-bồ béc-g-z in-x-tét-đ ơv p-lát-x-tíc.',
  u11_3: 'Pík-king ắp rắp-bít-sh kíp-s pác-k-s k-li-n.',
  u11_4: 'P-lêi-s ri-xai-k-ling bin-z in év-ri rum.',
  u11_5: 'Xai-k-ling ri-điut-xịt-z e-ơ pơ-lu-shừn.',
  u11_6: 'P-lan-t mo tri-z tu prơ-tếch-t k-lai-mịt.',
  u11_7: 'Xêy-v en-nơ-ji bai tơ-ning óph lait-s.',
  u11_8: 'Ri-điut-s phút-đ uêi-st tu xêy-v ri-zót-xịt-z.',
  u11_9: 'Diu-z kri-ê-típ-v ai-đi-ơ-z tu ri-xai-khồ.',
  u11_10: 'P-lan-ting tri-z hép-s x-tóp ph-lắt-đ-z.',

  // Unit 12
  u12_1: 'Rô-bót-ts khen đu mé-ni khom-p-lếch-s tát-x-k-s.',
  u12_2: 'Xăm rô-bót-ts hép bai oát-shing đít-shịt-z.',
  u12_3: 'Đe-ơ a rô-bót-ts đét-t ai-ừn kh-lâu-đ-z.',
  u12_4: 'Rô-bót-ts a diut-x-phun pho hiu-mừn-z.',
  u12_5: 'Ơ rô-bót iz ơ xpe-sồ x-mát-t mơ-sin.',
  u12_6: 'Hiu-mừn-z bin-đ en-đ khơn-trâu rô-bót-ts.',
  u12_7: 'Rô-bót-ts nít-đ i-lếch-trí-xi-ti tu ri-chát-d.',
  u12_8: 'Rô-bót-ts đu đê-li cho-z uýt-th-ao-t thai-ơ-đ.',
  u12_9: 'En-dơ-ni-ơ-z im-p-ru-v rô-bót-ts ơ-bí-lơ-tiz.',
  u12_10: 'Đi in-tơ-né-shơ-nồ rô-bó-tích-s khon-tét-st.',
};

// 3. Fallback Dictionary of Grade 6 English words to Vietnamese pronunciation
export const WORD_VIET_READING_MAP: Record<string, string> = {
  // Unit 1: My New School
  'ready': 'ré-đi',
  'new': 'niu',
  'meet': 'mít-t',
  'school': 'xcu-l (xờ-kun)',
  'heavy': 'hé-vi',
  'smart': 'x-mát-t',
  'special': 'xpe-sồ',
  'subject': 'xắp-dịch-t',
  'uniform': 'diu-ni-phom',
  'pencil sharpener': 'pen-sồ sa-pơ-nơ',
  'pencil case': 'pen-sồ cây-s',
  'rubber': 'rắp-bơ',
  'calculator': 'kheo-kiu-lây-tờ',
  'history': 'hít-xtơ-ri',
  'math': 'mát-th',
  'science': 'xai-ân-s',
  'compass': 'khăm-pớt-s',
  'classroom': 'kla-x-rum',
  'homework': 'hôm-uớc-k',
  'classmates': 'kla-x-mây-ts',
  'boarding school': 'bo-đinh xcu-l',
  'ruler': 'ru-lơ',

  // Unit 2: My House
  'living room': 'lí-ving rum',
  'bedroom': 'bét-rum',
  'kitchen': 'kít-chừn',
  'bathroom': 'bát-th-rum',
  'townhouse': 'tao-n-hao-s',
  'flat': 'ph-lét-t',
  'fridge': 'ph-rít-d',
  'dishwasher': 'đít-sh-oa-sơ',
  'chest of drawers': 'chét-st ơv đrô-z',
  'wardrobe': 'oa-đrô-b',
  'behind': 'bi-hain-đ',
  'between': 'bi-tuy-n',
  'in front of': 'in ph-răn-t ơv',
  'under': 'ăn-đờ',
  'bookshelf': 'búc-k-seo-ph',
  'decorate': 'đe-cơ-rây-t',
  'pillow': 'pí-lâu',
  'chopsticks': 'chóp-x-tích-s',

  // Unit 3: My Friends
  'friendly': 'ph-ren-đ-li',
  'clever': 'k-le-vờ',
  'kind': 'khain-đ',
  'creative': 'kri-ê-típ-v',
  'confident': 'khon-phi-đừn-t',
  'hard-working': 'hát-đ uếc-king',
  'shy': 'xai (shai)',
  'careful': 'khe-phun',
  'curly hair': 'khơ-li he-ơ',
  'blonde': 'b-lon-đ',
  'glasses': 'g-la-xịt-z',
  'picnic': 'píc-ních',
  'biscuit': 'bít-x-kịt',
  'active': 'éc-típ-v',
  'funny': 'phăn-ni',
  'comic book': 'khom-míc búc-k',
  'violin': 'vai-ơ-lin',

  // Unit 4: My Neighbourhood
  'neighbourhood': 'nây-bơ-hút-đ',
  'noisy': 'noi-zi',
  'quiet': 'quai-ợt',
  'lively': 'lai-v-li',
  'convenient': 'khơn-vi-ni-ừn-t',
  'cathedral': 'khơ-thi-đrồ',
  'temple': 'them-pồ',
  'railway station': 'rêu-uây x-tây-shừn',
  'square': 'x-que',
  'delicious': 'đi-li-shớt-s',
  'post office': 'pâu-xt óph-phịt-s',
  'museum': 'miu-zi-ừm',
  'crowded': 'k-rao-địt-đ',
  'narrow': 'ne-râu',
  'suburbs': 'xắp-bớp-z',

  // Unit 5: Natural Wonders of Viet Nam
  'wonder': 'oăn-đờ',
  'island': 'ai-lừn-đ',
  'waterfall': 'oa-tờ-pho',
  'cave': 'kêy-v',
  'desert': 'đe-zợt',
  'mountain': 'mao-n-từn',
  'sunscreen': 'xăn-x-kri-n',
  'sleeping bag': 'x-li-ping béc-g',
  'backpack': 'béc-k-péc-k',
  'plaster': 'p-la-x-tờ',
  'scissors': 'xít-zơ-z',
  'explore': 'ếch-x-p-lo',
  'scenery': 'xi-nơ-ri',
  'forest': 'pho-rịt-xt',

  // Unit 6: Our Tet Holiday
  'gatherings': 'gé-đơ-ring-z',
  'lucky money': 'lắc-ki ma-ni',
  'fireworks': 'phai-ơ-uếc-ks',
  'peach flowers': 'pít-ch ph-lao-uơ-z',
  'peach blossom': 'pít-ch b-la-xừm',
  'apricot blossom': 'ê-pri-khót b-la-xừm',
  'relatives': 're-lơ-típ-v-z',
  'envelopes': 'en-vơ-lâu-p-s',
  'customs': 'khắt-x-từm-z',
  'sweets': 'x-uýt-ts',
  'behave': 'bi-hêy-v',
  'midnight': 'mít-đ-nait',
  'wish': 'uýt-sh',
  'traditional': 'trờ-đít-shơ-nồ',
  'relative': 're-lơ-típ-v',
  'tradition': 'trờ-đi-shừn',
  'banh chung': 'bánh chưng',
  'calendar': 'khe-lừn-đờ',

  // Unit 7: Television
  'cartoon': 'kha-tun',
  'comedy': 'khom-mơ-đi',
  'channel': 'chen-nồ',
  'viewer': 'viu-ơ',
  'popular': 'pop-piu-lơ',
  'boring': 'bo-ring',
  'wildlife': 'uail-đ-laiph',
  'attract': 'ơ-tréc-kt',
  'intelligent': 'in-te-li-dừn-t',
  'talent show': 'te-lừn-t xô',
  'channel guide': 'chen-nồ gai-đ',
  'documentary': 'đóc-kiu-men-tơ-ri',
  'game show': 'gêm xô',
  'programme': 'prô-g-rem',
  'reporter': 'ri-pót-tờ',
  'remote control': 'ri-mâu-t khơn-trâu',
  'newsreader': 'niu-z-ri-đờ',
  'educational': 'e-ju-kêi-shơ-nồ',
  'entertaining': 'en-tơ-têi-ning',
  'character': 'khe-rơk-tờ',
  'schedule': 'x-ke-ju',

  // Unit 8: Sports and Games
  'table tennis': 'tê-bồ the-nịt-s',
  'karate': 'kơ-ra-ti',
  'volleyball': 'vo-li-bo',
  'chess': 'chét-s',
  'equipment': 'i-quíp-mừn-t',
  'champion': 'chem-pi-ừn',
  'racket': 'ré-kịt',
  'goggles': 'góg-gồ-z',
  'marathon': 'me-rơ-thon',
  'aerobics': 'e-rô-bích-s',
  'skipping rope': 'x-kíp-ping rô-p',
  'congratulations': 'khơn-g-rét-chu-lêi-shừn-z',
  'badminton': 'bét-min-từn',
  'basketball': 'bát-x-kịt-bo',
  'boxing': 'bóc-xinh',
  'cycling': 'xai-k-ling',
  'football': 'phút-bo',
  'gymnastics': 'dìm-nét-x-tích-s',
  'skateboard': 'x-kết-bo-đ',
  'swimming': 'xuy-m-ming',
  'stadium': 'x-tê-đi-ừm',

  // Unit 9: Cities of the World
  'landmark': 'len-đ-mác-k',
  'capital': 'khe-pi-tồ',
  'tower': 'thao-uơ',
  'ancient': 'ên-shừn-t',
  'postcard': 'pâu-xt-cát-đ',
  'coast': 'khôu-st',
  'visitor': 'ví-zi-tờ',
  'theater': 'thi-ơ-tờ',
  'exciting': 'ếch-xai-ting',
  'fantastic': 'phên-tát-x-tíc',
  'palace': 'pe-lợt-s',
  'floating market': 'ph-lâu-ting ma-kịt',
  'symbol': 'xim-bồ',
  'historic': 'hít-xtó-rích',

  // Unit 10: Houses in the Future
  'future': 'phiu-chờ',
  'solar': 'xô-lơ',
  'cottage': 'khót-tịt-d',
  'moon': 'mun',
  'appliance': 'ơ-p-lai-ừn-s',
  'helicopter': 'he-li-khóp-tờ',
  'planet': 'p-le-nịt',
  'electric': 'i-lếch-tríc',
  'automatic': 'o-tô-me-tích',
  'hi-tech': 'hai-tếch',
  'housework': 'hao-s-uớc',
  'motorhome': 'mô-tơ-hôm',
  'skyscraper': 'x-kai-x-krê-pơ',
  'smart home': 'x-mát-t hôm',
  'solar energy': 'xô-lơ en-nơ-ji',
  'space': 'x-pây-s',
  'submarine': 'xắp-mơ-ri-n',
  'supercar': 'xu-pơ-kha',
  'surround': 'xơ-rao-n-đ',
  'wireless': 'uai-ơ-lợt-s',

  // Unit 11: Our Greener World
  'environment': 'en-vai-rơn-mừn-t',
  'reusable': 'ri-diu-zơ-bồ',
  'rubbish': 'rắp-bít-sh',
  'recycling bins': 'ri-xai-k-ling bin-z',
  'plant': 'p-lan-t',
  'save': 'xêy-v',
  'waste': 'uêi-st',
  'floods': 'ph-lắt-đ-z',
  'recycle': 'ri-xai-khồ',
  'reduce': 'ri-điut-s',
  'reuse': 'ri-diut-z',
  'pollution': 'pơ-lu-shừn',
  'plastic bag': 'p-lát-x-tích béc-g',
  'bottle': 'bót-tồ',
  'charity': 'che-rơ-ti',
  'grow': 'g-râu',
  'protect': 'prơ-tếch-t',

  // Unit 12: Robots
  'robot': 'rô-bót-t',
  'do the dishes': 'đu đơ đít-shịt-z',
  'iron clothes': 'ai-ừn kh-lâu-đ-z',
  'useful': 'diut-x-phun',
  'machines': 'mơ-sin-z',
  'humans': 'hiu-mừn-z',
  'electricity': 'i-lếch-trí-xi-ti',
  'daily': 'đê-li',
  'improve': 'im-p-ru-v',
  'international': 'in-tơ-né-shơ-nồ',
  'laundry': 'lon-đri',
  'guard': 'gát-đ',
  'feed': 'phít-đ',
  'recognise': 'ré-khơg-naiz',
  'capable': 'kê-pơ-bồ',
  'opinion': 'ơ-pí-ni-ừn',
};

// 4. Token translation dictionary for sentence transliteration
const SENTENCE_WORD_MAP: Record<string, string> = {
  'are': 'a',
  'you': 'diu',
  'for': 'pho',
  'this': 'đít-s',
  'is': 'iz',
  'my': 'mai',
  'schoolbag': 'xcu-l-béc-g',
  'nice': 'nai-s',
  'to': 'tu',
  'he': 'hi',
  'she': 'xi',
  'it': 'ít',
  'they': 'đây',
  'we': 'uy',
  'goes': 'gâu-z',
  'every': 'év-ri',
  'day': 'đây',
  'days': 'đây-z',
  'the': 'đơ',
  'bag': 'béc-g',
  'looks': 'lúc-s',
  'very': 'vé-ri',
  'a': 'ơ',
  'an': 'ơn',
  'whats': 'óat-s',
  "what's": 'óat-s',
  'what': 'óat',
  'your': 'do',
  'favorite': 'phây-vơ-rịt',
  'favourite': 'phây-vơ-rịt',
  'pretty': 'prít-ti',
  'i': 'ai',
  'have': 'hép-v',
  'has': 'héz',
  'red': 'rét-đ',
  'colorful': 'kha-lơ-phun',
  'can': 'khen',
  'borrow': 'bo-râu',
  'fun': 'phăn',
  'and': 'en-đ',
  'exciting': 'ếch-xai-ting',
  'on': 'on',
  'mondays': 'măn-đây-z',
  'sundays': 'xăn-đây-z',
  'our': 'ao-ơ',
  'large': 'lát-d',
  'bright': 'b-rait',
  'hes': 'hi-z',
  "he's": 'hi-z',
  'doing': 'đu-inh',
  'his': 'hiz',
  'do': 'đu',
  'does': 'đắt-z',
  'remember': 'ri-mém-bơ',
  'study': 'x-tá-đi',
  'in': 'in',
  'short': 'so-t',
  'there': 'đe-ơ',
  'theres': 'đe-z',
  "there's": 'đe-z',
  'sofa': 'xô-pha',
  'cozy': 'khâu-zi',
  'house': 'hao-s',
  'houses': 'hao-zịt-z',
  'two': 'tu',
  'one': 'oăn',
  'bathrooms': 'bát-th-rum-z',
  'live': 'lip-v',
  'moving': 'mu-ving',
  'next': 'néch-st',
  'month': 'măn-th',
  'keep': 'kíp',
  'clothes': 'kh-lâu-đ-z',
  'mouse': 'mao-s',
  'box': 'bóc-x',
  'apple': 'ép-pồ',
  'blocks': 'b-lóc-s',
  'elephant': 'e-li-phừn-t',
  'chair': 'che-ơ',
  'dog': 'đóc-g',
  'table': 'tê-bồ',
  'big': 'bích-g',
  'christmas': 'krít-x-mợt-s',
  'tree': 'tri',
  'trees': 'tri-z',
  'cat': 'khet',
  'sleeping': 'x-li-ping',
  'bought': 'bo-t',
  'student': 'x-tiu-đừn-t',
  'boy': 'boi',
  'girl': 'gơ-l',
  'helpful': 'hép-phun',
  'artist': 'át-tịt-st',
  'stage': 'x-tê-d',
  'public': 'pắp-b-lích',
  'speak': 'x-píc',
  'please': 'p-li-z',
  'be': 'bi',
  'with': 'uýt-th',
  'that': 'đét-t',
  'brown': 'b-rao-n',
  'hair': 'he-ơ',
  'beautiful': 'biu-ti-phun',
  'wearing': 'ue-ring',
  'stylish': 'x-tai-lít-sh',
  'great': 'g-rêi-t',
  'together': 'tờ-gé-đơ',
  'pass': 'pát-s',
  'me': 'mi',
  'some': 'xăm',
  'biscuits': 'bít-x-kịt-s',
  'sports': 'x-pót-s',
  'makes': 'mêi-k-s',
  'us': 'ắt-s',
  'laugh': 'láp-ph',
  'reading': 'ri-đinh',
  'comic': 'khom-míc',
  'book': 'búc-k',
  'playing': 'p-lê-inh',
  'village': 'ví-lịt-d',
  'street': 'x-trít',
  'place': 'p-lêi-s',
  'take': 'thêi-k',
  'bus': 'bắt-s',
  'often': 'óp-phừn',
  'go': 'gâu',
  'should': 'xút-đ',
  'visit': 'ví-zịt',
  'ngoc': 'ngọc',
  'son': 'sơn',
  'busy': 'bí-zi',
  'town': 'thao-n',
  'seafood': 'xi-phút-đ',
  'here': 'hi-ơ',
  'wheres': 'ue-z',
  "where's": 'ue-z',
  'where': 'ue-ơ',
  'once': 'oăn-s',
  'was': 'uơ-z',
  'too': 'tu',
  'alley': 'e-li',
  'of': 'ơv',
  'da': 'đà',
  'nang': 'nẵng',
  'vietnam': 'việt nam',
  'viet': 'việt',
  'nam': 'nam',
  'many': 'mé-ni',
  'islands': 'ai-lừn-đ-z',
  'which': 'uýt-ch',
  'cao': 'cao',
  'bang': 'bằng',
  'doong': 'đoòng',
  'magnificent': 'méc-ní-phi-xừn-t',
  'were': 'uơ',
  '9': 'nai-n',
  'nine': 'nai-n',
  'fansipan': 'phan-xi-păng',
  'highest': 'hai-ịt-st',
  'apply': 'ơ-p-lai',
  'before': 'bi-pho',
  'going': 'gâu-inh',
  'out': 'ao-t',
  'warm': 'uo-m',
  'blue': 'b-lu',
  'supplies': 'xơ-p-lai-z',
  'got': 'gót',
  'cut': 'khắt',
  'her': 'hơ',
  'could': 'khút-đ',
  'want': 'oăn-t',
  'boat': 'bâu-t',
  'by': 'bai',
  'scenery': 'xi-nơ-ri',
  'wonderful': 'oăn-đơ-phun',
  'love': 'lắp-v',
  'hiking': 'hai-king',
  'green': 'g-ri-n',
  'tet': 'tết',
  'time': 'thaim',
  'family': 'phe-mơ-li',
  'youll': 'diu-l',
  "you'll": 'diu-l',
  'get': 'gét',
  'watch': 'oát-ch',
  'start': 'x-tát',
  'starts': 'x-tát-s',
  'light': 'lait',
  'up': 'ắp',
  'sky': 'x-kai',
  'flowers': 'ph-lao-uơ-z',
  'make': 'mêi-k',
  'good': 'gút-đ',
  'wishes': 'uýt-shịt-z',
  'others': 'á-đơ-z',
  'relatives': 're-lơ-típ-v-z',
  'bring': 'b-ring',
  'luck': 'lắc',
  'include': 'in-k-lu-đ',
  'cleaning': 'k-li-ning',
  'home': 'hôm',
  'children': 'chiu-đrừn',
  'enjoy': 'in-dôi',
  'eating': 'ít-ting',
  'well': 'ueo',
  'during': 'điu-ring',
  'at': 'ét',
  'wear': 'ue',
  'ao': 'áo',
  'dai': 'dài',
  'prefers': 'pri-phơ-z',
  'watching': 'oát-ching',
  'cartoons': 'kha-tun-z',
  'movies': 'mu-viz',
  'network': 'nét-uớc-k',
  'famous': 'phê-mớt-s',
  'viewers': 'viu-ơ-z',
  'entertaining': 'en-tơ-têi-ning',
  'shows': 'xô-z',
  'show': 'xô',
  'most': 'môu-st',
  'film': 'phim',
  'about': 'ơ-bao-t',
  'teach': 'tít-ch',
  'nature': 'nê-chờ',
  'tv': 'ti-vi',
  'attracts': 'ơ-tréc-kts',
  'dolphins': 'đon-phin-z',
  'animals': 'e-ni-mồ-z',
  'music': 'miu-zíc',
  'check': 'chếch-k',
  'guide': 'gai-đ',
  'tonight': 'tờ-nait',
  'plays': 'p-lê-z',
  'afternoon': 'áp-tơ-nun',
  'morning': 'mo-ning',
  'team': 'tim',
  'sport': 'x-pót',
  'mind': 'main-đ',
  'gym': 'dim',
  'lots': 'lót-s',
  'basketball': 'bát-x-kịt-bo',
  'champion': 'chem-pi-ừn',
  'swung': 'xoăng',
  'swimming': 'xuy-m-ming',
  'goggles': 'góg-gồ-z',
  'trained': 'trên-đ',
  'aerobic': 'e-rô-bíc',
  'exercises': 'ék-sơ-saiz-z',
  'kids': 'khít-đ-z',
  'fit': 'phịt-t',
  'practiced': 'prác-tít-st',
  'victory': 'vík-tơ-ri',
  'ben': 'ben',
  'london': 'lơn-đơn',
  'capital': 'khe-pi-tồ',
  'city': 'xi-ti',
  'eiffel': 'ép-phen',
  'paris': 'pa-ri',
  'hoi': 'hội',
  'streets': 'x-trít-s',
  'sent': 'xen-t',
  'postcard': 'pâu-xt-cát-đ',
  'sydney': 'sít-ni',
  'clean': 'k-li-n',
  'coasts': 'khôu-sts',
  'thousands': 'thau-zừn-đ-z',
  'daily': 'đê-li',
  'opera': 'ó-pơ-ra',
  'theater': 'thi-ơ-tờ',
  'exploring': 'ếch-x-p-lo-ring',
  'tokyo': 'tô-ky-ô',
  'view': 'viu',
  'fantastic': 'phên-tát-x-tíc',
  'robots': 'rô-bót-ts',
  'robot': 'rô-bót-t',
  'chores': 'cho-z',
  'automatically': 'o-tô-me-tíc-li',
  'will': 'uyn',
  'panels': 'pe-nồ-z',
  'roofs': 'rup-ph-s',
  'like': 'lai-k',
  'palaces': 'pe-lợt-xịt-z',
  'cottage': 'khót-tịt-d',
  'imagine': 'i-me-dìn',
  'living': 'lí-ving',
  'dome': 'đôm',
  'moon': 'mun',
  'appliances': 'ơ-p-lai-ừn-xịt-z',
  'save': 'xêy-v',
  'energy': 'en-nơ-ji',
  'rooftop': 'ruf-tóp',
  'pads': 'pát-đ-z',
  'helicopters': 'he-li-khóp-tơ-z',
  'must': 'mắt-st',
  'protect': 'prơ-tếch-t',
  'planet': 'p-le-nịt',
  'electric': 'i-lếch-tríc',
  'help': 'hép',
  'cook': 'khúc-k',
  'protecting': 'prơ-tếch-ting',
  'duty': 'điu-ti',
  'use': 'diu-z',
  'reusable': 'ri-diu-zơ-bồ',
  'bags': 'béc-g-z',
  'instead': 'in-x-tét-đ',
  'plastic': 'p-lát-x-tíc',
  'picking': 'pík-king',
  'keeps': 'kíp-s',
  'parks': 'pác-k-s',
  'bins': 'bin-z',
  'room': 'rum',
  'cycling': 'xai-k-ling',
  'reduces': 'ri-điut-xịt-z',
  'air': 'e-ơ',
  'pollution': 'pơ-lu-shừn',
  'plant': 'p-lan-t',
  'planting': 'p-lan-ting',
  'more': 'mo',
  'climate': 'k-lai-mịt',
  'turning': 'tơ-ning',
  'off': 'óph',
  'lights': 'lait-s',
  'reduce': 'ri-điut-s',
  'food': 'phút-đ',
  'waste': 'uêi-st',
  'resources': 'ri-zót-xịt-z',
  'creative': 'kri-ê-típ-v',
  'ideas': 'ai-đi-ơ-z',
  'recycle': 'ri-xai-khồ',
  'helps': 'hép-s',
  'stop': 'x-tóp',
  'floods': 'ph-lắt-đ-z',
  'complex': 'khom-p-lếch-s',
  'tasks': 'tát-x-k-s',
  'washing': 'oát-shing',
  'dishes': 'đít-shịt-z',
  'iron': 'ai-ừn',
  'useful': 'diut-x-phun',
  'humans': 'hiu-mừn-z',
  'machine': 'mơ-sin',
  'build': 'bin-đ',
  'control': 'khơn-trâu',
  'need': 'nít-đ',
  'electricity': 'i-lếch-trí-xi-ti',
  'recharge': 'ri-chát-d',
  'without': 'uýt-th-ao-t',
  'tired': 'thai-ơ-đ',
  'engineers': 'en-dơ-ni-ơ-z',
  'improve': 'im-p-ru-v',
  'abilities': 'ơ-bí-lơ-tiz',
  'robotics': 'rô-bó-tích-s',
  'contest': 'khon-tét-st',
};

/**
 * Gets the curated Vietnamese reading for an example sentence.
 */
export function getVietnameseSentenceReading(sentence: string, wordId?: string): string {
  if (wordId && EXACT_SENTENCE_VIET_READING_BY_ID[wordId]) {
    return EXACT_SENTENCE_VIET_READING_BY_ID[wordId];
  }

  if (!sentence) return '';

  // Clean and split words while preserving punctuation
  const words = sentence.trim().split(/\s+/);
  const translated = words.map((token) => {
    // extract punctuation
    const match = token.match(/^([^a-zA-Z0-9']*)([a-zA-Z0-9']+)([^a-zA-Z0-9']*)$/);
    if (!match) return token;

    const prefix = match[1] || '';
    const cleanWord = match[2].toLowerCase();
    const suffix = match[3] || '';

    let viet = SENTENCE_WORD_MAP[cleanWord] || WORD_VIET_READING_MAP[cleanWord];

    if (!viet) {
      // Fallback heuristics for common endings & forms
      if (cleanWord.endsWith("'s")) {
        const base = cleanWord.slice(0, -2);
        const baseViet = SENTENCE_WORD_MAP[base] || WORD_VIET_READING_MAP[base] || base;
        viet = `${baseViet}-s`;
      } else if (cleanWord.endsWith('s') && (SENTENCE_WORD_MAP[cleanWord.slice(0, -1)] || WORD_VIET_READING_MAP[cleanWord.slice(0, -1)])) {
        const base = cleanWord.slice(0, -1);
        const baseViet = SENTENCE_WORD_MAP[base] || WORD_VIET_READING_MAP[base];
        viet = `${baseViet}-s`;
      } else if (cleanWord.endsWith('ed') && (SENTENCE_WORD_MAP[cleanWord.slice(0, -2)] || WORD_VIET_READING_MAP[cleanWord.slice(0, -2)])) {
        const base = cleanWord.slice(0, -2);
        const baseViet = SENTENCE_WORD_MAP[base] || WORD_VIET_READING_MAP[base];
        viet = `${baseViet}-đ`;
      } else if (cleanWord.endsWith('ing') && (SENTENCE_WORD_MAP[cleanWord.slice(0, -3)] || WORD_VIET_READING_MAP[cleanWord.slice(0, -3)])) {
        const base = cleanWord.slice(0, -3);
        const baseViet = SENTENCE_WORD_MAP[base] || WORD_VIET_READING_MAP[base];
        viet = `${baseViet}-inh`;
      } else {
        viet = cleanWord;
      }
    }

    return `${prefix}${viet}${suffix}`;
  });

  const result = translated.join(' ');
  return result.charAt(0).toUpperCase() + result.slice(1);
}

/**
 * Gets the curated Vietnamese reading for a vocabulary word.
 */
export function getVietnameseWordReading(word: string, wordId?: string): string {
  if (wordId && EXACT_WORD_VIET_READING_BY_ID[wordId]) {
    return EXACT_WORD_VIET_READING_BY_ID[wordId];
  }

  if (!word) return '';
  const key = word.trim().toLowerCase();
  if (WORD_VIET_READING_MAP[key]) {
    return WORD_VIET_READING_MAP[key];
  }

  // Split multiple words if any
  const parts = key.split(/\s+/);
  if (parts.length > 1) {
    return parts.map(p => WORD_VIET_READING_MAP[p] || SENTENCE_WORD_MAP[p] || p).join(' ');
  }

  return key;
}
